# Generated by Django 2.0.4 on 2018-04-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecionar_carro', models.TextField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMINHAO', 'Caminhão'), ('NAUTICO', 'Nautico')], max_length=10)),
                ('selecionar_marca', models.TextField(max_length=10)),
                ('ano', models.TextField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField(verbose_name='Data da Solicitação')),
                ('nome', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('bairro', models.TextField(max_length=200)),
                ('telefone', models.TextField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
