# Generated by Django 2.0 on 2018-06-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segurodetail',
            name='choice_dano',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segurodetail',
            name='choice_reboque_distancia',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segurodetail',
            name='choice_reembolso',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segurodetail',
            name='choice_reserva',
            field=models.CharField(choices=[('7', '7 dias'), ('10', '14 dias')], default=1, max_length=2, verbose_name='carro_reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segurodetail',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segurodetail',
            name='fipe_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.FipeDetail'),
        ),
    ]
