# Generated by Django 2.0.4 on 2018-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20180428_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='date_register',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
